name: "GLPI development environment image"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/glpi-development-env.yml"
      - "glpi-development-env/**"
  pull_request:
    paths:
      - ".github/workflows/glpi-development-env.yml"
      - "glpi-development-env/**"
  schedule:
    - cron:  '0 0 * * 1'
  # Enable manual run
  workflow_dispatch:

env:
  DOCKER_IMAGES_REPO: ${{ vars.DOCKER_IMAGES_REPO || 'glpi-project/docker-images' }}
  DOCKERHUB_DEV_IMAGE: ${{ vars.DOCKERHUB_DEV_IMAGE || 'glpi/glpi-development-env' }}
  GHCR_DEV_IMAGE: ${{ vars.GHCR_DEV_IMAGE || 'ghcr.io/glpi-project/glpi-development-env' }}

jobs:
  prepare:
    name: "Prepare"
    runs-on: "ubuntu-latest"
    outputs:
      push: ${{ steps.set-vars.outputs.push }}
    steps:
      - name: "Set variables"
        id: "set-vars"
        run: |
          PUSH="false"
          if [[ "${{ github.ref }}" = 'refs/heads/main' && "${{ github.repository }}" = "${{ env.DOCKER_IMAGES_REPO }}" ]]; then
              PUSH="true"
          fi
          echo "push=$PUSH" >> $GITHUB_OUTPUT

  build:
    runs-on: "ubuntu-latest"
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        include:
          - {base-image: "php:7.4-apache-bullseye", php-version: "7.4", latest: "false"}
          - {base-image: "php:8.0-apache-bullseye", php-version: "8.0", latest: "false"}
          - {base-image: "php:8.1-apache-trixie", php-version: "8.1", latest: "false"}
          - {base-image: "php:8.2-apache-trixie", php-version: "8.2", latest: "false"}
          - {base-image: "php:8.3-apache-trixie", php-version: "8.3", latest: "false"}
          - {base-image: "php:8.4-apache-trixie", php-version: "8.4", latest: "false"}
          - {base-image: "php:8.5-apache-trixie", php-version: "8.5", latest: "true"}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"
      - name: "Login to DockerHub"
        if: ${{ needs.prepare.outputs.push == 'true' }}
        uses: "docker/login-action@v3"
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"
      - name: "Login to Github container registry"
        if: ${{ needs.prepare.outputs.push == 'true' }}
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{ secrets.GHCR_USERNAME }}"
          password: "${{ secrets.GHCR_ACCESS_TOKEN }}"
      - name: "Build and push"
        uses: "docker/build-push-action@v6"
        with:
          build-args: |
             BASE_IMAGE=${{ matrix.base-image }}
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"
          context: "glpi-development-env"
          outputs: "type=image,push=${{ needs.prepare.outputs.push }}"
          pull: true
          tags: "${{ env.GHCR_DEV_IMAGE }}:${{ matrix.php-version }}${{ matrix.latest == 'true' && format(',{0}:latest', env.GHCR_DEV_IMAGE) || '' }}"
